In [2]:
import numpy
world_alcohol=numpy.genfromtxt("world_alcohol.txt",delimiter=",")
print(world_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.987e+03       nan       nan       nan 7.500e-01]
 [1.989e+03       nan       nan       nan 1.500e+00]
 [1.985e+03       nan       nan       nan 3.100e-01]]


In [3]:
print(world_alcohol[1,4])

0.0


In [4]:
vector=numpy.array([5,10,15,20])
print(vector[0:3])

[ 5 10 15]


In [3]:
matrix=numpy.array([[5, 10, 15], [20, 25, 30], [35, 40,45]])
print(matrix[:,1])
print(matrix[:,0:2]) 

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]


In [6]:
matrix=numpy.array([[5, 10, 15], [20, 25, 30], [35, 40,45]])
matrix==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [11]:
vector=numpy.array([5,10,15,20])
equal_to_ten=(vector==10)
print(equal_to_ten)
vector[equal_to_ten]

[False  True False False]


array([10])

In [20]:
vector=numpy.array([5,10,15,20])
equal_to_ten=(vector==10) | (vector==5)
print(equal_to_ten)

[ True  True False False]


In [21]:
vector=numpy.array([5,10,15,20])
vector.dtype

dtype('int32')

In [23]:
vector=numpy.array([5,10,15,20])
print(vector.mean())
print(vector.max())

12.5
20


axis=1行相加 axis=0 列相加

In [2]:
import numpy
matrix=numpy.array([[5, 10, 15], 
                    [20, 25, 30], 
                    [35, 40,45]])
matrix.sum(axis=1)


array([ 30,  75, 120])

In [25]:
matrix=numpy.array([[5, 10, 15], 
                    [20, 25, 30], 
                    [35, 40,45]])
matrix.sum(axis=0)

array([60, 75, 90])

test

In [3]:
import numpy
world_alcohol=numpy.genfromtxt("world_alcohol.txt",delimiter=",")
#print(world_alcohol)
ls_value_empty=numpy.nan_to_num(world_alcohol[:,4])
#print(ls_value_empty)
alcohol_consumption=numpy.nan_to_num(world_alcohol[:,4])
alcohol_consumption=alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.000e+00 0.000e+00 5.000e-01 1.620e+00 4.270e+00 1.980e+00 0.000e+00
 1.300e-01 3.900e-01 1.550e+00 6.100e+00 2.000e-01 6.200e-01 0.000e+00
 0.000e+00 5.000e-02 7.000e-02 6.000e-02 2.230e+00 1.620e+00 1.080e+00
 0.000e+00 4.510e+00 2.670e+00 4.400e-01 0.000e+00 0.000e+00 1.360e+00
 2.220e+00 1.100e-01 0.000e+00 4.480e+00 0.000e+00 1.600e+00 0.000e+00
 8.000e-01 2.240e+00 7.000e-02 3.040e+00 0.000e+00 1.000e-02 1.900e+00
 6.820e+00 3.060e+00 3.000e-02 0.000e+00 1.900e-01 2.260e+00 4.000e-02
 7.000e-01 1.490e+00 3.000e-01 3.880e+00 0.000e+00 0.000e+00 1.810e+00
 4.000e-02 0.000e+00 5.100e+00 0.000e+00 0.000e+00 0.000e+00 8.000e-02
 0.000e+00 0.000e+00 1.260e+00 0.000e+00 1.000e-02 0.000e+00 1.200e-01
 4.200e-01 1.020e+00 5.700e-01 0.000e+00 1.000e-02 2.060e+00 0.000e+00
 2.000e-02 1.000e-02 0.000e+00 2.090e+00 8.400e-01 2.540e+00 2.250e+00
 0.000e+00 0.000e+00 1.000e-02 1.830e+00 1.000e-02 4.200e-01 7.000e-01
 1.000e-02 4.430e+00 0.000e+00 0.000e+00 3.060e+00 0.000e+00 7.380e+00
 0.000

test123


In [4]:
import numpy as np

print(np.arange(15))
a=np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [13]:
a=np.arange(15).reshape(1,3,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


In [14]:
a.ndim

3

In [17]:
a.dtype

dtype('int32')

In [18]:
a.size

15

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.random.random((2,3))

array([[0.31006636, 0.44656133, 0.38257048],
       [0.82748992, 0.24556873, 0.09116956]])

In [24]:
np.random.random((2,3))*2-1

array([[-0.0201549 , -0.41533507,  0.55679227],
       [-0.7442946 , -0.54595304,  0.97520691]])

In [25]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [26]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

c=a-b
print(c)

c=c-1
print(c)

print(b**2)
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]


In [29]:
a=np.array([[1,1],
           [0,1]])
b=np.array([[2,1],
           [3,4]])
print(a)
print('----------------')
print(b)
print('----------------')
print(a*b)
print('----------------')

print(a.dot(b))
print('----------------')
print(np.dot(a,b))

[[1 1]
 [0 1]]
----------------
[[2 1]
 [3 4]]
----------------
[[2 1]
 [0 4]]
----------------
[[5 5]
 [3 4]]
----------------
[[5 5]
 [3 4]]


In [1]:
import numpy as np
b=np.arange(3)
print(b)
#numpy.exp()：返回e的幂次方，e是一个常数为2.71828
print(np.exp(b))
#取根号
print(np.sqrt(b))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [9]:
#floor向下取整
a=np.floor(10*np.random.random((3,4)))
print(a)
print('===============矩阵转向量================')
print(a.ravel())
print('===============矩阵转向量================')
a.shape=(6,2)
print(a)
print('===============转置================')
print(a.T)
print('===============矩阵结构确定可以用-1表示，不用计算================')
a.shape=(6,-1)
print(a)

[[1. 9. 5. 1.]
 [8. 6. 1. 8.]
 [6. 0. 1. 2.]]
===============矩阵转向量================
[1. 9. 5. 1. 8. 6. 1. 8. 6. 0. 1. 2.]
===============矩阵转向量================
[[1. 9.]
 [5. 1.]
 [8. 6.]
 [1. 8.]
 [6. 0.]
 [1. 2.]]
===============转置================
[[1. 5. 8. 1. 6. 1.]
 [9. 1. 6. 8. 0. 2.]]
===============矩阵转向量================
[[1. 9.]
 [5. 1.]
 [8. 6.]
 [1. 8.]
 [6. 0.]
 [1. 2.]]


In [11]:
a=np.floor(10*np.random.random((3,4)))
b=np.floor(10*np.random.random((3,4)))
print(a)
print(b)
print('=======按行拼接==========')
print(np.hstack((a,b)))
print('=======按列拼接==========')
print(np.vstack((a,b)))

[[1. 7. 7. 2.]
 [9. 4. 5. 1.]
 [2. 0. 6. 1.]]
[[0. 7. 0. 3.]
 [8. 6. 5. 8.]
 [2. 1. 9. 3.]]
=======按行拼接==========
[[1. 7. 7. 2. 0. 7. 0. 3.]
 [9. 4. 5. 1. 8. 6. 5. 8.]
 [2. 0. 6. 1. 2. 1. 9. 3.]]
=======按列拼接==========
[[1. 7. 7. 2.]
 [9. 4. 5. 1.]
 [2. 0. 6. 1.]
 [0. 7. 0. 3.]
 [8. 6. 5. 8.]
 [2. 1. 9. 3.]]


In [16]:
a=np.floor(10*np.random.random((2,12)))
print(a)
print('=======按行切分==========')
print(np.hsplit(a,3))
print('=======按行在3,4之间切了一刀==========')
print(np.hsplit(a,(3,4)))
print('=======按列切分==========')
a=np.floor(10*np.random.random((12,2)))
print(a)

print(np.vsplit(a,3))

[[8. 9. 9. 1. 3. 1. 1. 2. 2. 6. 4. 0.]
 [5. 5. 3. 4. 9. 4. 8. 5. 6. 5. 7. 6.]]
=======按行切分==========
[array([[8., 9., 9., 1.],
       [5., 5., 3., 4.]]), array([[3., 1., 1., 2.],
       [9., 4., 8., 5.]]), array([[2., 6., 4., 0.],
       [6., 5., 7., 6.]])]
=======按行在3,4之间切了一刀==========
[array([[8., 9., 9.],
       [5., 5., 3.]]), array([[1.],
       [4.]]), array([[3., 1., 1., 2., 2., 6., 4., 0.],
       [9., 4., 8., 5., 6., 5., 7., 6.]])]
=======按列切分==========
[[0. 1.]
 [5. 9.]
 [2. 2.]
 [4. 6.]
 [7. 1.]
 [7. 4.]
 [8. 4.]
 [5. 0.]
 [3. 7.]
 [4. 4.]
 [6. 5.]
 [3. 3.]]
[array([[0., 1.],
       [5., 9.],
       [2., 2.],
       [4., 6.]]), array([[7., 1.],
       [7., 4.],
       [8., 4.],
       [5., 0.]]), array([[3., 7.],
       [4., 4.],
       [6., 5.],
       [3., 3.]])]


In [18]:
b=a
print (b is a)
#浅复制,但值依然公用一个空间
c=a.view()
print (c is a)
d=a.copy()
print(a)
print (d is a)
d[0,0]=999
print(d)

True
False
[[0. 1.]
 [5. 9.]
 [2. 2.]
 [4. 6.]
 [7. 1.]
 [7. 4.]
 [8. 4.]
 [5. 0.]
 [3. 7.]
 [4. 4.]
 [6. 5.]
 [3. 3.]]
False
[[999.   1.]
 [  5.   9.]
 [  2.   2.]
 [  4.   6.]
 [  7.   1.]
 [  7.   4.]
 [  8.   4.]
 [  5.   0.]
 [  3.   7.]
 [  4.   4.]
 [  6.   5.]
 [  3.   3.]]


In [22]:
data=np.sin(np.arange(20)).reshape(5,4)
print(data)
#按列去最大值
ind=data.argmax(axis=0)
print(ind)
print(data.shape[1])
#把最大值列出来
data_max=data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
4
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [24]:
a=np.arange(0,40,10)
print(a)
#tile复制a 2行4列
b=np.tile(a,(2,4))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [29]:
a=np.array([[4,3,5],[1,2,1]])
#1按行排序 0 按列排序
b=np.sort(a,axis=1)
print(b)

[[3 4 5]
 [1 1 2]]
