In [2]:
import numpy
world_alcohol=numpy.genfromtxt("world_alcohol.txt",delimiter=",")
print(world_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.987e+03       nan       nan       nan 7.500e-01]
 [1.989e+03       nan       nan       nan 1.500e+00]
 [1.985e+03       nan       nan       nan 3.100e-01]]


In [4]:
print(world_alcohol[1,4])

0.0


In [5]:
vector=numpy.array([5,10,15,20])
print(vector[0:3])

[ 5 10 15]


In [7]:
matrix=numpy.array([[5, 10, 15], [20, 25, 30], [35, 40,45]])
print(matrix[:,1])
print(matrix[:,0:2]) 

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]


In [ ]:
matrix=numpy.array([[5, 10, 15], [20, 25, 30], [35, 40,45]])
matrix==25

In [11]:
vector=numpy.array([5,10,15,20])
equal_to_ten=(vector==10)
print(equal_to_ten)
vector[equal_to_ten]

[False  True False False]


array([10])

In [20]:
vector=numpy.array([5,10,15,20])
equal_to_ten=(vector==10) | (vector==5)
print(equal_to_ten)

[ True  True False False]


In [21]:
vector=numpy.array([5,10,15,20])
vector.dtype

dtype('int32')

In [23]:
vector=numpy.array([5,10,15,20])
print(vector.mean())
print(vector.max())

12.5
20


In [24]:
matrix=numpy.array([[5, 10, 15], 
                    [20, 25, 30], 
                    [35, 40,45]])
matrix.sum(axis=1)


array([ 30,  75, 120])

In [25]:
matrix=numpy.array([[5, 10, 15], 
                    [20, 25, 30], 
                    [35, 40,45]])
matrix.sum(axis=0)

array([60, 75, 90])

In [31]:
import numpy
world_alcohol=numpy.genfromtxt("world_alcohol.txt",delimiter=",")
#print(world_alcohol)
ls_value_empty=numpy.nan_to_num(world_alcohol[:,4])
#print(ls_value_empty)
alcohol_consumption=numpy.nan_to_num(world_alcohol[:,4])
alcohol_consumption=alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.000e+00 0.000e+00 5.000e-01 1.620e+00 4.270e+00 1.980e+00 0.000e+00
 1.300e-01 3.900e-01 1.550e+00 6.100e+00 2.000e-01 6.200e-01 0.000e+00
 0.000e+00 5.000e-02 7.000e-02 6.000e-02 2.230e+00 1.620e+00 1.080e+00
 0.000e+00 4.510e+00 2.670e+00 4.400e-01 0.000e+00 0.000e+00 1.360e+00
 2.220e+00 1.100e-01 0.000e+00 4.480e+00 0.000e+00 1.600e+00 0.000e+00
 8.000e-01 2.240e+00 7.000e-02 3.040e+00 0.000e+00 1.000e-02 1.900e+00
 6.820e+00 3.060e+00 3.000e-02 0.000e+00 1.900e-01 2.260e+00 4.000e-02
 7.000e-01 1.490e+00 3.000e-01 3.880e+00 0.000e+00 0.000e+00 1.810e+00
 4.000e-02 0.000e+00 5.100e+00 0.000e+00 0.000e+00 0.000e+00 8.000e-02
 0.000e+00 0.000e+00 1.260e+00 0.000e+00 1.000e-02 0.000e+00 1.200e-01
 4.200e-01 1.020e+00 5.700e-01 0.000e+00 1.000e-02 2.060e+00 0.000e+00
 2.000e-02 1.000e-02 0.000e+00 2.090e+00 8.400e-01 2.540e+00 2.250e+00
 0.000e+00 0.000e+00 1.000e-02 1.830e+00 1.000e-02 4.200e-01 7.000e-01
 1.000e-02 4.430e+00 0.000e+00 0.000e+00 3.060e+00 0.000e+00 7.380e+00
 0.000